### ISSUE TITLE
Found few missing translation

### ISSUE THREAD

**Issue by misa1515** [emsesp/EMS-ESP32#2369]
### DESCRIPTION

_A clear and concise description of what the problem is or the change requested._

### REQUESTED INFORMATION

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Searched the issue in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [x] Searched the issue in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [x] Searched the issue in the [docs](https://docs.emsesp.org/Troubleshooting/)
- [x] Searched the issue in the [chat](https://discord.gg/3J3GgnzpyT)
- [x] Provide the System information in the area below, taken from `http://<IP>/api/system`

### SCREENSHOTS  

![Image](https://github.com/user-attachments/assets/c4515e65-5c46-4f60-9e66-d976e7bb30e1)

![Image](https://github.com/user-attachments/assets/7280177a-a40a-4e99-90d3-2e0c1a08fa16)

**Comment by proddy** [comment]
this is fixed in later 3.7.2 releases. See demo at https://demo.emsesp.org/settings/version

**Comment by misa1515** [comment]
Please check it again, still missing translation for marked text on first picture. 
"pletform" and "release type"

**Comment by proddy** [comment]
> Please check it again, still missing translation for marked text on first picture. "pletform" and "release type"

you're right. I'll add them!

**Comment by misa1515** [comment]
thank you for feedback.

**Comment by proddy** [comment]
added

**Comment by proddy** [comment]
oh yeah, will fix that
