### ISSUE TITLE
Command switchtimeww: 00 mo 10:00 on failed (Invalid)

### ISSUE THREAD

**Issue by JokerGermany** [emsesp/EMS-ESP32#2490]
### DESCRIPTION

Tired to set the time for switchtimeww, like i have done for hc1 hc2 and circulated pump
See https://github.com/emsesp/EMS-ESP32/discussions/2473
But when I use the same syntax the ems-esp website give me this error:
Request Failed

This is in the Log (set the log to info)
2025-03-25 17:00:39.559 W 412: [telegram] Incomplete Rx: C4 08 00 34 00 3C 02 2A 02 2A 21 00 01 03 00 04 E8 4B 00 C5 89 00 4C
2025-03-25 17:00:40.695 W 413: [command] Command switchtimeww: 00 mo 10:00 on failed (Invalid)

_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Searched the issue in [issues](https://github.com/emsesp/EMS-ESP32/issues)
- [x] Searched the issue in [discussions](https://github.com/emsesp/EMS-ESP32/discussions)
- [x] Searched the issue in the [docs](https://docs.emsesp.org/Troubleshooting/)
- [ ] Searched the issue in the [chat](https://discord.gg/3J3GgnzpyT) (I don't use discord)
- [x] Provide the System information in the area below, taken from `http://<IP>/api/system`

```json
{"system":{"version":"3.7.2","uptime":"000+00:26:01.848","uptimeSec":1561,"platform":"ESP32","cpuType":"ESP32-D0WD","arduino":"Tasmota Arduino v2.0.17","sdk":"4.4.8.240628","freeMem":156,"maxAlloc":79,"freeCaps":109,"usedApp":1650,"freeApp":334,"partition":"app0","flash_chip_size":4096,"resetReason":"Software reset CPU / Software reset CPU","psram":false,"model":""},"network":{"network":"WiFi","hostname":"ems-esp","RSSI":-83,"WIFIReconnects":0,"TxPowerSetting":78,"staticIP":true,"lowBandwidth":false,"disableSleep":true,"enableMDNS":false,"enableCORS":false,"APProvisionMode":"disconnected","APSecurity":"wpa2","APSSID":"ems-esp"},"ntp":{"NTPStatus":"connected","enabled":true,"server":"ptbtime1.ptb.de","tzLabel":"Europe/Amsterdam"},"mqtt":{"MQTTStatus":"connected","MQTTPublishes":1284,"MQTTQueued":0,"MQTTPublishFails":0,"MQTTReconnects":0,"enabled":true,"clientID":"ems-esp","keepAlive":60,"cleanSession":false,"entityFormat":4,"base":"ems-esp","discoveryPrefix":"homeassistant","discoveryType":0,"nestedFormat":2,"haEnabled":true,"mqttQos":0,"mqttRetain":false,"publishTimeHeartbeat":60,"publishTimeBoiler":0,"publishTimeThermostat":0,"publishTimeSolar":0,"publishTimeMixer":0,"publishTimeWater":10,"publishTimeOther":10,"publishTimeSensor":0,"publishSingle":false,"publish2command":false,"sendResponse":false},"syslog":{"enabled":false},"sensor":{"temperatureSensors":0,"temperatureSensorReads":0,"temperatureSensorFails":0,"analogSensors":0,"analogSensorReads":0,"analogSensorFails":0},"api":{"APICalls":0,"APIFails":0},"bus":{"busStatus":"connected","busProtocol":"Buderus","busTelegramsReceived":2434,"busReads":667,"busWrites":124,"busIncompleteTelegrams":54,"busReadsFailed":0,"busWritesFailed":0,"busRxLineQuality":100,"busTxLineQuality":100},"settings":{"boardProfile":"CUSTOM","locale":"de","txMode":1,"emsBusID":11,"showerTimer":true,"showerMinDuration":180,"showerAlert":false,"phyType":0,"rxGPIO":5,"txGPIO":17,"dallasGPIO":4,"pbuttonGPIO":33,"ledGPIO":2,"ledType":0,"hideLed":true,"noTokenApi":false,"readonlyMode":false,"fahrenheit":false,"dallasParasite":false,"boolFormat":4,"boolDashboard":3,"enumFormat":1,"analogEnabled":true,"telnetEnabled":true,"maxWebLogBuffer":25,"modbusEnabled":false,"forceHeatingOff":false,"developerMode":false},"devices":[{"type":"boiler","name":"BK13/BK15, Smartline, GB1*2","deviceID":"0x08","productID":64,"brand":"","version":"03.02","entities":74,"handlersReceived":"0x10 0x11 0x15 0x1C 0x18 0x19 0x34 0x04","handlersFetched":"0x14 0x16 0x33","handlersPending":"0xBF 0xC2 0x1A 0x35 0x26 0x2A 0xD1 0xE3 0xE4 0xE5 0xE6 0xE9 0xEA 0x28 0x2E 0x3B","handlersIgnored":"0x1E"},{"type":"thermostat","name":"RC30","deviceID":"0x10","productID":67,"brand":"","version":"02.08","entities":82,"handlersReceived":"0xA3 0x06 0xA2 0x12 0x38 0x39","handlersFetched":"0x3E 0x3D 0x3F 0x48 0x47 0x49 0xA5 0x37","handlersPending":"0x13 0x42 0x4C 0x52 0x51 0x53 0x56 0x5C 0x5B 0x5D 0x60"},{"type":"mixer","name":"MM10","deviceID":"0x21","productID":69,"brand":"","version":"02.00","entities":6,"handlersReceived":"0xAB","handlersFetched":"0xAA","handlersPending":"0xAC"},{"type":"switch","name":"WM10","deviceID":"0x11","productID":71,"brand":"","version":"02.00","entities":3,"handlersReceived":"0x9C","handlersPending":"0x9D 0x1E"},{"type":"controller","name":"BC10, RFM20","deviceID":"0x09","productID":68,"brand":"","version":"02.02","entities":0,"handlersIgnored":"0x29"}]}
```

### TO REPRODUCE
set  switchtimeww e.g.
00 mo 10:00 on

### EXPECTED BEHAVIOUR

accept the command and show
00 mo 10:00 on

**Comment by MichaelDvP** [comment]
Hmm, should be `dhw/switchtime`, but something has gone wrong, it's now `dhw/switchtimeww` and the mqtt shortname contains uppercase:
https://github.com/emsesp/EMS-ESP32/blob/e006bebb86973ab52826a153797f849f83b4933e/src/core/locale_translations.h#L655
I'll fix...

**Comment by MichaelDvP** [comment]
Please try https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest with `dhw/switchtime`

**Comment by JokerGermany** [comment]
will try, btw was already not working with 3.7.1

**Comment by JokerGermany** [comment]
Same, but the now it's Error instead of invalid
`2025-03-25 19:15:13.655 W 23: [command] Command switchtime: 00 mo 10:00 on failed (Error)`

**Comment by MichaelDvP** [comment]
Do you mean this? 
![Image](https://github.com/user-attachments/assets/7eccc870-f16e-46ff-a9a2-8d78de13b65d)

**Comment by JokerGermany** [comment]
yes, this is missing for me

**Comment by MichaelDvP** [comment]
`dhw/progmode` should be fixed in https://github.com/MichaelDvP/EMS-ESP32/releases/tag/latest

**Comment by JokerGermany** [comment]
Yes thanks

![Image](https://github.com/user-attachments/assets/0d889e8e-aa61-45a6-8f41-dd741392b790)

The switchtime error is still there
2025-03-26 10:49:25.619 W 24: [command] Command switchtime: 00 mo 10:00 on failed (Error)
2025-03-26 10:49:36.279 W 25: [telegram] Incomplete Rx: C4 08 00 34 00 3C 02 45 02 45 21 00 05 03 00 04 E8 C9 00 C5 9C 00 EA

**Comment by MichaelDvP** [comment]
Ok, now the command should work in my build, please check.

**Comment by JokerGermany** [comment]
Looks good, will test a litte bit more with this:
https://github.com/emsesp/EMS-ESP32/discussions/2473
